"""
Generates the KiCad schematic of the 4S battery monitor / protector board:
TI BQ76920 analog front end (cell voltages, current, temperature, balancing,
FET drivers), low-side charge/discharge MOSFETs, 1 mOhm current shunt, and
the I2C connector to the microcontroller that runs firmware/.

    python hardware/gen_afe.py   ->   hardware/afe/bms_afe.kicad_sch

Component values follow the BQ76920 datasheet (SLUSBK2I) recommended
operating conditions; the reasoning for each is in the notes on the sheet.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import kisch  # noqa: E402

OUT = HERE / "afe"
OUT.mkdir(exist_ok=True)

s = kisch.Schematic("4S Li-ion BMS - BQ76920 analog front end + protection FETs", "bms_afe", "A3")
s.date, s.rev = "2026-10-07", "A"
s.comments = ["4x LG HG2 18650 in series (16.8 V max), 22 A discharge / 4.5 A charge",
              "Firmware: firmware/ (EKF SOC, protection, balancing) on the MCU at J3",
              "Generated by hardware/gen_afe.py"]
FP = {"R0603": "Resistor_SMD:R_0603_1608Metric", "R2512": "Resistor_SMD:R_2512_6332Metric",
      "C0603": "Capacitor_SMD:C_0603_1608Metric", "C1206": "Capacitor_SMD:C_1206_3216Metric",
      "SOD123": "Diode_SMD:D_SOD-123", "SMB": "Diode_SMD:D_SMB",
      "FET": "Package_SON:VSONP-8-1EP_5x6_P1.27mm", "TSSOP20": "Package_SO:TSSOP-20_4.4x6.5mm_P0.65mm",
      "J5": "Connector_JST:JST_XH_B5B-XH-A_1x05_P2.50mm_Vertical",
      "J6": "Connector_PinHeader_2.54mm:PinHeader_1x06_P2.54mm_Vertical",
      "J2": "Connector_AMASS:AMASS_XT60-M_1x02_P7.20mm_Vertical",
      "FUSE": "Fuse:FuseHolder_Blade_ATO_Littelfuse_FLR_178.6165"}


def R(v, x, y, a, b, rot=0, fp="R0603"):
    return s.add("Device:R", "R", v, x, y, rot, {"1": a, "2": b}, FP[fp])


def C(v, x, y, a, b, rot=0, fp="C0603"):
    return s.add("Device:C", "C", v, x, y, rot, {"1": a, "2": b}, FP[fp])


def flag(net, x, y):
    s.add("power:PWR_FLAG", "#FLG", "PWR_FLAG", x, y, 0, {"1": net}, hide_value=True)


# ---- cell connector + input filters ---------------------------------------------
s.text("CELL TAPS + INPUT FILTERS", 20, 22, 2.0, True)
s.add("Connector_Generic:Conn_01x05", "J", "cell taps", 30, 55, 0,
      {"1": "CELL4", "2": "CELL3", "3": "CELL2", "4": "CELL1", "5": "CELL0"}, FP["J5"])
s.text("J1: B+ (cell 4 +), 3+, 2+, 1+, B-", 20, 67, 1.3)
taps = [("CELL0", "VC0_F"), ("CELL1", "VC1_F"), ("CELL2", "VC2_F"), ("CELL3", "VC3_F"), ("CELL4", "VC5_F")]
for k, (a, b) in enumerate(taps):
    R("43", 60 + 12 * k, 40, a, b)
for k, (a, b) in enumerate((("VC1_F", "VC0_F"), ("VC2_F", "VC1_F"), ("VC3_F", "VC2_F"), ("VC5_F", "VC3_F"))):
    C("1u", 60 + 12 * k, 72, a, b)
s.text("Rc = 43 ohm, Cc = 1 uF per cell (datasheet range 40-1k ohm / 0.1-10 uF).", 55, 86, 1.3)
s.text("Rc also sets the internal balancing current: 4.1 V / (2 x 43 + ~4) ohm = 45 mA.", 55, 90, 1.3)
s.text("4 cells on a BQ76920: VC4 is shorted to VC3 (datasheet Table 9-2).", 55, 94, 1.3)

# ---- supply ------------------------------------------------------------------------
s.text("SUPPLY", 20, 110, 2.0, True)
R("100", 30, 125, "CELL4", "BAT_F")
C("10u 25V", 48, 125, "BAT_F", "VSS", fp="C1206")
C("1u", 66, 125, "BAT_F", "VSS")
C("1u", 84, 125, "CAP1", "VSS")
C("4.7u", 102, 125, "3V3_AFE", "VSS")
s.text("BAT filter Rf = 100 ohm / Cf = 10 uF; REGSRC tied to BAT; REGOUT = 3.3 V for the MCU side", 20, 140, 1.3)
flag("VSS", 120, 118)
flag("BAT_F", 132, 118)

# ---- the AFE -------------------------------------------------------------------------
s.text("BQ76920 ANALOG FRONT END", 150, 22, 2.0, True)
s.add("Battery_Management:BQ76920PW", "U", "BQ7692003PW", 175, 70, 0,
      {"17": "VC0_F", "16": "VC1_F", "15": "VC2_F", "14": "VC3_F", "13": "VC3_F", "12": "VC5_F",
       "10": "BAT_F", "9": "BAT_F", "8": "3V3_AFE", "7": "CAP1", "6": "TS1", "3": "VSS",
       "18": "SRP_F", "19": "SRN_F", "4": "SDA", "5": "SCL", "20": "ALERT", "1": "DSG_DRV",
       "2": "CHG_DRV", "11": None}, FP["TSSOP20"])
s.text("14-bit cell ADC (382 uV LSB), 16-bit coulomb counter (8.44 uV LSB),", 150, 100, 1.3)
s.text("hardware OV / UV / OCD / SCD protection, internal cell balancing", 150, 104, 1.3)

# temperature + boot + alert
s.add("Device:Thermistor_NTC", "TH", "10k 103AT", 140, 120, 0, {"1": "TS1", "2": "VSS"}, FP["R0603"])
R("1k", 158, 120, "BOOT", "TS1")
R("1M", 176, 120, "ALERT", "VSS")
s.text("TS1: NTC on the cells; a rising edge from BOOT wakes the AFE from SHIP mode", 135, 132, 1.3)

# ---- MCU connector -------------------------------------------------------------------
s.text("TO THE MCU (runs firmware/)", 250, 22, 2.0, True)
s.add("Connector_Generic:Conn_01x06", "J", "MCU I2C", 265, 50, 0,
      {"1": "3V3_AFE", "2": "SDA", "3": "SCL", "4": "ALERT", "5": "BOOT", "6": "VSS"}, FP["J6"])
R("10k", 285, 40, "3V3_AFE", "SDA")
R("10k", 297, 40, "3V3_AFE", "SCL")
s.text("J3: 3.3 V, SDA, SCL, ALERT, BOOT, GND", 250, 66, 1.3)

# ---- current sense + protection FETs ----------------------------------------------------
s.text("CURRENT SENSE + LOW-SIDE PROTECTION FETs", 150, 150, 2.0, True)
R("1m 2W", 160, 175, "VSS", "SNS", fp="R2512")
R("100", 175, 165, "VSS", "SRP_F", 90)
R("100", 175, 185, "SNS", "SRN_F", 90)
C("100n", 190, 175, "SRP_F", "SRN_F")
s.text("1 mOhm shunt: OCD 22.2 mV = 22 A, SCD 66.6 mV = 67 A, 8.4 mA resolution", 150, 198, 1.3)
s.add("Transistor_FET:Q_NMOS_GDS", "Q", "CSD18540Q5B", 240, 180, 0,
      {"1": "DSG_G", "2": "FET_MID", "3": "SNS"}, FP["FET"])
R("100", 225, 170, "DSG_DRV", "DSG_G", 90)
R("1M", 225, 190, "DSG_G", "SNS")
s.add("Transistor_FET:Q_NMOS_GDS", "Q", "CSD18540Q5B", 290, 180, 180,
      {"1": "CHG_G", "2": "FET_MID", "3": "PACK-"}, FP["FET"])
R("4.7k", 310, 170, "CHG_DRV", "CHG_G", 90)
R("1M", 310, 190, "CHG_G", "PACK-")
s.add("Device:D_Zener", "D", "15 V", 322, 190, 90, {"1": "CHG_G", "2": "PACK-"}, FP["SOD123"])
s.text("Q1/Q2: CSD18540Q5B, 60 V, 1.8 mOhm (0.9 W at 22 A). Back-to-back FETs: DSG blocks discharge,", 150, 210, 1.3)
s.text("CHG blocks charge; each body diode lets the other direction flow, so a tripped pack can", 150, 214, 1.3)
s.text("still be charged after an under-voltage trip or discharged after an over-voltage trip.", 150, 218, 1.3)

# ---- pack terminals ------------------------------------------------------------------------
s.text("PACK TERMINALS", 20, 170, 2.0, True)
s.add("Device:Fuse", "F", "30 A", 35, 190, 0, {"1": "CELL4", "2": "PACK+"}, FP["FUSE"])
s.add("Device:D_TVS", "D", "SMBJ20A", 60, 190, 90, {"1": "PACK-", "2": "PACK+"}, FP["SMB"])
s.add("Connector_Generic:Conn_01x02", "J", "PACK", 90, 190, 0, {"1": "PACK+", "2": "PACK-"}, FP["J2"])
s.text("TVS clamps the inductive kick when a FET opens under load", 20, 205, 1.3)

s.write(OUT / "bms_afe.kicad_sch")
pro = OUT / "bms_afe.kicad_pro"
if not pro.exists():
    pro.write_text(json.dumps({"meta": {"filename": "bms_afe.kicad_pro", "version": 1}}, indent=2))
print("wrote", OUT / "bms_afe.kicad_sch")
