"""
Step 5 - export the cell model to C for the firmware.

Writes firmware/src/cell_tables.h: OCV and the 2-RC parameters on a uniform
41-point SOC grid (every 2.5 %), as float constants. The firmware EKF looks
values up with linear interpolation, the same way the Python model does.
"""
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from bms.model import CellModel                          # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
N = 41
m = CellModel.load(ROOT / "data" / "cell_model.json")
grid = np.linspace(0, 1, N)
cols = {"OCV": m.ocv_at(grid), "R0": np.interp(grid, m.soc, m.r0), "R1": np.interp(grid, m.soc, m.r1),
        "TAU1": np.interp(grid, m.soc, m.tau1), "R2": np.interp(grid, m.soc, m.r2),
        "TAU2": np.interp(grid, m.soc, m.tau2)}


def arr(name, vals, unit):
    body = ",\n    ".join(", ".join(f"{v:.6g}f" for v in vals[k:k + 6]) for k in range(0, len(vals), 6))
    return f"/* {unit} */\nstatic const float CELL_{name}[CELL_TABLE_N] = {{\n    {body}\n}};\n"


text = f"""/*
 * cell_tables.h - GENERATED by scripts/05_export_tables.py, do not edit.
 *
 * LG HG2 18650 cell model fitted to lab data (McMaster University test data,
 * CC BY 4.0). Index k corresponds to SOC = k / (CELL_TABLE_N - 1).
 */
#ifndef CELL_TABLES_H
#define CELL_TABLES_H

#define CELL_TABLE_N {N}
#define CELL_CAPACITY_AH {m.q_ah:.5f}f

{arr("OCV", cols["OCV"], "open-circuit voltage, V")}
{arr("R0", cols["R0"], "series resistance, ohm")}
{arr("R1", cols["R1"], "fast RC resistance, ohm")}
{arr("TAU1", cols["TAU1"], "fast RC time constant, s")}
{arr("R2", cols["R2"], "slow RC resistance, ohm")}
{arr("TAU2", cols["TAU2"], "slow RC time constant, s")}
#endif
"""
out = ROOT / "firmware" / "src" / "cell_tables.h"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(text)
# the same tables as a Python model, used as the reference in the SIL test
ref = CellModel(q_ah=m.q_ah, soc=grid, ocv=cols["OCV"], r0=cols["R0"], r1=cols["R1"], tau1=cols["TAU1"],
                r2=cols["R2"], tau2=cols["TAU2"], meta={"note": "41-point firmware tables"})
ref.save(ROOT / "data" / "cell_model_firmware.json")
print("wrote", out)
